---
pr:
  lifecycleLabels:
    ignoreDrafts: true
    labels:
      reviewRequired: "status: needs review"
      changesRequested: "status: changes requested"
      moreReviewsRequired: "status: needs more reviews"
      reviewStarted: "status: review started"
      approved: "status: approved"
      merged: "status: merged"
  conventionalTitle:
    rules:
      'header-max-length': [2, 'always', 80]
  tasksList:
  autoApprove:
    allBots: false
    users: ['thegreatsourcerer', 'thegreatsourcerer2']
